name: Build

on:
  pull_request:
    branches:
    - master
    - API*

  push:
    branches:
    - master
    - API*
    paths:
    - 'build/**'
    - 'internals/**'
    - 'src/**'
    - 'tools/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Env
      run: env

    - uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
