name: "Build Target"

on:
  pull_request_target:
    branches:
    - master
    - API*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x

    - name: Test
      run: |
        env
        ls -l
