name: "Check API Level"

on:
  pull_request_target:
    branches:
    - master
    - API*

jobs:
  AddLabels:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: master

    - uses: TizenAPI/tizenfx-build-actions/branch-metadata@master
      id: metadata
      with:
        ref: ${{ github.base_ref }}

    - name: Add Label
      if: ${{ steps.metadata.outputs.data }}
      uses: actions/github-script@v2
      with:
        script: |
          console.log(${{ steps.metadata.outputs.data }})
          var metadata = JSON.parse(${{ steps.metadata.outputs.data }})
          console.log(metadata)
          console.log(metadata.labels)



    # - name: Add Label
    #   if: ${{ steps.metadata.outputs.data }}
    #   uses: actions/github-script@v2
    #   with:
    #     script: |
    #       github.issues.addLabels({
    #         issue_number: context.issue.number,
    #         owner: context.repo.owner,
    #         repo: context.repo.repo,
    #         labels: ${{ fromJSON(steps.metadata.outputs.data).labels }}
    #       })
