name: "Check API Level"

on:
  pull_request_target:
    branches:
    - master
    - API*

jobs:
  AddLabels:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: master

    - uses: TizenAPI/tizenfx-build-actions/branch-metadata@master
      id: metadata
      with:
        ref: ${{ github.base_ref }}

    - name: Test
      run: |
        echo ${{ fromJSON(steps.metadata.outputs.data).api-level }}
        echo ${{ steps.metadata.outputs.data.api-level }}

    - name: Add Label
      if: ${{ steps.metadata.outputs.data }}
      uses: actions/github-script@v2
      env:
        BRANCH_METADATA: ${{ steps.metadata.outputs.data }}
      with:
        script: |
          var metadata = JSON.parse(process.env.BRANCH_METADATA)
          github.issues.addLabels({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            labels: metadata.labels
          })
