name: "Postback Pull Request"

on:
  workflow_run:
    workflows: ["Build Pull Request"]
    types:
      - completed

jobs:
  postback:
    runs-on: ubuntu-latest
    steps:

    - name: Info
      run: |
        env
        echo "${{ github.event.workflow_run }}"

    - name: Download Artifacts from Build
      uses: TizenAPI/tizenfx-build-actions/download-workflow-artifacts@master
      with:
        token: ${{ secrets.TIZENAPI_BOT_PAT }}
        run-id: ${{ github.event.workflow_run.id }}
        name: artifact
        path: Artifacts

    - name: Show Files
      run: ls -R
