name: "Build Target"

on:
  pull_request_target:
    branches:
    - master
    - API*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Information
      run: |
        echo "PR NO: ${{ github.event.pull_request.number }}"
        echo "PR REPO: ${{ github.event.pull_request.head.repo.full_name }}"
        echo "PR_SHA: ${{ github.event.pull_request.head.sha }}"
    - uses: actions/checkout@v2
      with:
        ref: refs/remotes/pull/${{ github.event.pull_request.number }}/merge
    - name: List Files
      run: |
        ls -l
        env
    - name: Add Label
      uses: actions/github-script@v2
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          github.issues.addLabels({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            labels: ["mytest"]
          })
