name: Release

on:
  workflow_dispatch:
    inputs:
      target:
        description: 'Release Branch'
        required: true
        default: 'master'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.event.inputs.target }}
        fetch-depth: 0

    - name: Get Metadata of Release Branch
      uses: TizenAPI/tizenfx-build-actions/branch-metadata@master
      id: metadata
      with:
        ref: ${{ github.event.inputs.target }}

    - name: Get Version
      id: version
      env:
        VERSION_PREFIX: ${{ steps.metadata.output.version-prefix }}
      run: |
        VERSION=$VERSION_PREFIX.$((10000+$(git rev-list --count HEAD)))
        echo VERSION=$VERSION
        echo "::set-output name=version::$VERSION"

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x

    - name: Build
      run: ./build.sh full

    - name: Pack
      env:
        VERSION: ${{ steps.get-version.outputs.version }}
      run: ./build.sh pack $VERSION

    - name: Upload NuGet Packages
      env:
        NUGET_SOURCE: https://tizen.myget.org/F/dotnet-test/api/v2/package
        APIKEY: ${{ secrets.MYGET_APIKEY }}
        VERSION:
      run: |
        for p in Artifacts/*.nupkg; do
          echo dotnet nuget push $p -k $APIKEY -s $NUGET_SOURCE -t 3000
        done

    - name: Setup SSH Private Keys
      uses: webfactory/ssh-agent@v0.4.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY_FOR_GERRIT }}

    - name: Sync To Gerrit
      env:
        VERSION: ${{ steps.version.outputs.version }}
        TARGET_BRANCH: ${{ github.event.inputs.target }}
        GERRIT_BRANCH: ${{ steps.metadata.outputs.tizen-branch }}
        GERRIT_URL: ssh://dotnetbuild@review.tizen.org:29418/platform/core/csapi/tizenfx
      run: |
        git config --global user.name "TizenAPI-Bot"
        git config --global user.email "tizenapi@samsung.com"
        git config core.sshCommand "ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no"
        git remote add gerrit $GERRIT_URL
        git fetch gerrit $GERRIT_BRANCH
        git checkout -t gerrit/$GERRIT_BRANCH
        git merge --no-edit -s recursive -X theirs origin/$TARGET_BRANCH
        ./packaging/makespec.sh -r $VERSION -n $VERSION -i $VERSION
        git add packaging/
        if [ $(git diff --cached --numstat | wc -l) -eq 0 ]; then
          echo "## no changes to sync"
          exit 0
        fi
        SUBMIT_TAG=submit/$GERRIT_BRANCH/$(date '+%Y%m%d.%H%M%S')
        echo SUBMIT_TAG=$SUBMIT_TAG
        git commit -m "Release $VERSION"
        echo git push -f gerrit HEAD:$GERRIT_BRANCH
        git tag -m "Release $VERSION" $SUBMIT_TAG
        echo git push gerrit refs/tags/$SUBMIT_TAG